### ISSUE TITLE
Error trying to run - Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession

### ISSUE THREAD

**Issue by xandrmoro** [metal3d/ComfyUI_Human_Parts#3]
ERROR - !!! Exception during processing !!! This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
2024-10-28 00:24:41,299 - root - ERROR - Traceback (most recent call last):
  File "I:\ai\comfyui\comfy\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "I:\ai\comfyui\comfy\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "I:\ai\comfyui\comfy\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\ai\comfyui\comfy\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "I:\ai\comfyui\comfy\custom_nodes\ComfyUI_Human_Parts\nodes.py", line 89, in get_mask
    model = ort.InferenceSession(model_path)
  File "C:\Users\morot\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
    raise e
  File "C:\Users\morot\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\morot\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by metal3d** [comment]
Thanks to report this!

I'm currently working on another implementation, but I'm busy by another complex project.

**Comment by metal3d** [comment]
I really cannot reproduce the error. I'm using onnxruntime 1.20.1 and the error is not present.
